feat: comment branch validate

diff --git a/.github/workflows/setup.yml b/.github/workflows/setup.yml
--- a/.github/workflows/setup.yml
+++ b/.github/workflows/setup.yml
@@ -17,21 +17,21 @@ on:
         value: ${{ jobs.preflight_checklist.outputs.gitversion }}
 
 jobs:
-  validate_branch_name:
-    name: validate branch name 
-    runs-on: live
-    if: ${{ inputs.squad && (github.event_name == 'pull_request' || (github.event_name == 'push' && github.ref_type == 'branch')) }}
-    steps:
-      - name: Set squad variable
-        id: set-squad
-        run: |
-          echo "SQUAD=${{ inputs.squad }}" >> $GITHUB_ENV
+  # validate_branch_name:
+  #   name: validate branch name 
+  #   runs-on: live
+  #   if: ${{ inputs.squad && (github.event_name == 'pull_request' || (github.event_name == 'push' && github.ref_type == 'branch')) }}
+  #   steps:
+  #     - name: Set squad variable
+  #       id: set-squad
+  #       run: |
+  #         echo "SQUAD=${{ inputs.squad }}" >> $GITHUB_ENV
 
-      - name: validate branch name
-        if: ${{ env.SQUAD != 'cabal' && env.SQUAD != 'hive' && env.SQUAD != 'fallen' && env.SQUAD != 'vex' && env.SQUAD != 'taken'}}
-        run: |
-             echo "::error::Branch name doesn't match the required pattern"
-             exit 1
+  #     - name: validate branch name
+  #       if: ${{ env.SQUAD != 'cabal' && env.SQUAD != 'hive' && env.SQUAD != 'fallen' && env.SQUAD != 'vex' && env.SQUAD != 'taken'}}
+  #       run: |
+  #            echo "::error::Branch name doesn't match the required pattern"
+  #            exit 1
 
   preflight_checklist:
     name: preflight checklist
