chore: setup

diff --git a/.github/workflows/setup.yml b/.github/workflows/setup.yml
--- a/.github/workflows/setup.yml
+++ b/.github/workflows/setup.yml
@@ -11,7 +11,7 @@ on:
         type: string
         required: false
         default: 'false'
-      squad:
+      squad_name:
         type: string
         required: false
     outputs:
@@ -30,16 +30,16 @@ jobs:
     steps:
       - name: squad name output
         id: squad_name_output
-        run: echo "squad_name=${{ inputs.project_name }}" >> "$GITHUB_OUTPUT"
+        run: echo "squad_name=${{ inputs.squad_name }}" >> "$GITHUB_OUTPUT"
 
-      - name: squad name output
+      - name: debug
         run: echo $squad_name
 
-      # - name: validate branch name
-      #   if: ${{ !($SQUAD_NAME == 'cabal' || $SQUAD_NAME == 'hive' || $SQUAD_NAME == 'fallen' || $SQUAD_NAME == 'vex' || $SQUAD_NAME == 'eval') }}
-      #   run: |
-      #        echo "::error::Branch name doesn't match the required pattern"
-      #        exit 1
+      - name: validate branch name
+        if: ${{ !($squad_name == 'cabal' || $squad_name == 'hive' || $squad_name == 'fallen' || $squad_name == 'vex' || $squad_name == 'eval') }}
+        run: |
+             echo "::error::Branch name doesn't match the required pattern"
+             exit 1
     outputs:
       squad_name: ${{ steps.squad_name_output.outputs.squad_name }}
 
