chore: setup

diff --git a/.github/workflows/setup.yml b/.github/workflows/setup.yml
--- a/.github/workflows/setup.yml
+++ b/.github/workflows/setup.yml
@@ -30,11 +30,11 @@ jobs:
         run: echo ${{ inputs.squad }}
 
       - name: validate branch name
-        # if: ${{ !(inputs.squad == 'cabal' || inputs.squad == 'hive' || inputs.squad == 'fallen' || inputs.squad == 'vex' || inputs.squad == 'eval') }}
-        if: ${{ (inputs.squad != 'hive' || inputs.squad != 'cabal') }}
         run: |
-             echo "::error::Branch name doesn't match the required pattern"
-             exit 1
+          if [[ !inputs.squad == 'cabal' || inputs.squad == 'hive' || inputs.squad == 'fallen' || inputs.squad == 'vex' || inputs.squad == 'eval' ]]; then
+               echo "::error::Branch name doesn't match the required pattern"
+               exit 1
+          fi
 
   preflight_checklist:
     name: preflight checklist
