chore: debug

diff --git a/.github/workflows/setup.yml b/.github/workflows/setup.yml
--- a/.github/workflows/setup.yml
+++ b/.github/workflows/setup.yml
@@ -31,11 +31,15 @@ jobs:
           squad_name=$(echo "${{ github.event.pull_request.head.ref }}" | cut -d "-" -f 1)
           echo "SQUAD_NAME=$squad_name" >> $GITHUB_OUTPUT
 
-      - name: validate branch name
-        if: ${{ !($SQUAD_NAME == 'cabal' || $SQUAD_NAME == 'hive' || $SQUAD_NAME == 'fallen' || $SQUAD_NAME == 'vex' || $SQUAD_NAME == 'eval') }}
-        run: |
-             echo "::error::Branch name doesn't match the required pattern"
-             exit 1
+      - name: squad name output
+        id: squad_name_output
+        run: echo $SQUAD_NAME
+
+      # - name: validate branch name
+      #   if: ${{ !($SQUAD_NAME == 'cabal' || $SQUAD_NAME == 'hive' || $SQUAD_NAME == 'fallen' || $SQUAD_NAME == 'vex' || $SQUAD_NAME == 'eval') }}
+      #   run: |
+      #        echo "::error::Branch name doesn't match the required pattern"
+      #        exit 1
     outputs:
       squad_name: ${{ steps.squad_name_output.outputs.squad_name }}
 
