chore: setup

diff --git a/.github/workflows/setup.yml b/.github/workflows/setup.yml
--- a/.github/workflows/setup.yml
+++ b/.github/workflows/setup.yml
@@ -25,10 +25,9 @@ jobs:
     steps:
       - name: validate branch name
         if: ${{ !(inputs.squad == 'cabal' || inputs.squad == 'hive' || inputs.squad == 'fallen' || inputs.squad == 'vex' || inputs.squad == 'eval') }}
-        run: echo "::error::Branch name doesn't match the required pattern"
-          - exit 1
-      # - name: validate branch name
-      #   if: ${{ !(inputs.squad == 'cabal' || inputs.squad == 'hive' || inputs.squad == 'fallen' || inputs.squad == 'vex' || inputs.squad == 'eval') }}
+        run: |
+             echo "::error::Branch name doesn't match the required pattern"
+             exit 1
       # - name: squad name output
       #   run: 
 
